source 'https://github.com/CocoaPods/Specs.git'
platform :ios, ’9.0’
use_frameworks!

target 'RGSwiftProject' do

    pod 'Alamofire'
    pod 'Cache'
    pod 'CryptoSwift'
    pod 'SnapKit'         # 自动布局封装
    pod 'Kingfisher'
    pod 'ESTabBarController-swift'

end

