source 'https://github.com/CocoaPods/Specs.git'
platform :ios, ’9.0’
use_frameworks!

target 'RGSwiftProject' do

    pod 'Moya'
    pod 'SnapKit'         # 自动布局封装
    pod 'Toast-Swift'
    pod 'Kingfisher'

end

